
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotik.GUI;
import apotik.DataBeanList;
import apotik.kasir;
import apotik.kasir;
import apotik.konekDB;
import static apotik.konekDB.con;
import apotik.obatdata;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat; 
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Aang
 */
public class belanjaa extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    DefaultTableModel tab;
    obatdata obat = new obatdata();
    List<obatdata> dataObat = new ArrayList<>();
    konekDB db = new konekDB();
    String id, harga;
    int totalharga;
    DataBeanList beanList = new DataBeanList();
    
  public belanjaa() {
        initComponents();
        this.setExtendedState(belanjaa.MAXIMIZED_BOTH);
        buatTabel();
        tampilTabel();
        db.config();
    }
    
     private void buatTabel() {
        tab = new DefaultTableModel();
        tab.addColumn("ID");
        tab.addColumn("Nama Obat");
        tab.addColumn("Harga");

       
        tabeldat.setModel(tab);
        //Untuk mengatur lebar kolom
        tabeldat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);                
        tabeldat.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabeldat.getColumnModel().getColumn(1).setPreferredWidth(300);        
        tabeldat.getColumnModel().getColumn(2).setPreferredWidth(200);        
       
    }
    
     private void tampilTabel() {
        dataObat.clear();
        dataObat = obat.tampil();
        for (int x = 0; x < dataObat.size(); x++) {
            Object[] data = new Object[3];
            data[0] = dataObat.get(x).getid();
            data[1] = dataObat.get(x).getNamaobat();
            data[2] = dataObat.get(x).getHarga();
            tab.addRow(data);
        }
    }
   
    public int getTotalHarga(){
   
    int row = tabelbelanjaan.getRowCount();
    int totalharga = 0;
      for (int i =0; i< row; i++){
          totalharga = totalharga + Integer.parseInt((String)tabelbelanjaan.getValueAt(i, 2).toString());
      }
      return totalharga;
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        keluar = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbelanjaan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pencarian = new javax.swing.JTextField();
        totharga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(240, 190, 90));

        keluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        tabelbelanjaan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelbelanjaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Obat", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabelbelanjaan);

        tabeldat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabeldat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabeldat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldat);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apotek/images/barumed.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pencarian");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Daftar Belanjaan");

        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });
        pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pencarianKeyPressed(evt);
            }
        });

        totharga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totharga.setText(" ");
        totharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tothargaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total Harga");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(totharga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(81, 81, 81)
                                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(191, 191, 191))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totharga, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabeldatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldatMouseClicked
    TableModel model = tabeldat.getModel();
      int index[]=tabeldat.getSelectedRows();
      Object[] row = new Object[3];
      DefaultTableModel model2 = (DefaultTableModel) tabelbelanjaan.getModel();
      int baris= tabelbelanjaan.getRowCount();
   
      for(int i=0; i<index.length; i++){
          String no = String.valueOf(baris+1);
          
          row[0]=no;
          row[1]=model.getValueAt(index[i], 1).toString(); 
          row[2]=model.getValueAt(index[i], 2).toString();
          model2.addRow(row);
     
          String a = (String) model.getValueAt(index[i], 0);
          String b = (String) model.getValueAt(index[i], 2);
          String c = (String) model.getValueAt(index[i], 1);
          beanList.addBean(c, Integer.parseInt(b));
          db.insert(a, b);
      }
      
      totharga.setText(Integer.toString(getTotalHarga()));
    }//GEN-LAST:event_tabeldatMouseClicked

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
        login login = new login();
        login.setVisible(true);
    }//GEN-LAST:event_keluarActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        kasir k = new kasir();
        k.printStruk(beanList,getTotalHarga());
    }//GEN-LAST:event_printActionPerformed

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianActionPerformed

    private void pencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianKeyPressed
        DefaultTableModel tab= new DefaultTableModel(); // mendeklarasikan class yang digunakan untuk memberi header dan data
            tab.addColumn("ID"); // menambahkan kolom
            tab.addColumn("Nama Obat");
            tab.addColumn("Harga");
            tabeldat.setModel(tab);
        //Untuk mengatur lebar kolom
        tabeldat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);                
        tabeldat.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabeldat.getColumnModel().getColumn(1).setPreferredWidth(300);        
        tabeldat.getColumnModel().getColumn(2).setPreferredWidth(200);        
       

            
        try{
            String sql = "SELECT * FROM dataobat WHERE id LIKE '%"+pencarian.getText()+
                    "%' or nama_obat LIKE '%"+pencarian.getText()+
                    "%' or harga LIKE '%"+pencarian.getText()+
                    "%'";
            st=con.createStatement();
            rs=st.executeQuery(sql);
            
            while(rs.next()){ 
                tab.addRow(new Object[]{
                rs.getString("id"), rs.getString("nama_obat"),rs.getString("harga")
                });
            }
            tabeldat.setModel(tab);
        }catch(Exception e){
            System.out.println(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_pencarianKeyPressed

    private void tothargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tothargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tothargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(belanjaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(belanjaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(belanjaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(belanjaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new belanjaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField pencarian;
    private javax.swing.JButton print;
    private javax.swing.JTable tabelbelanjaan;
    private javax.swing.JTable tabeldat;
    private javax.swing.JTextField totharga;
    // End of variables declaration//GEN-END:variables
}
